INFO       - 2023-09-12 13:40:05,415 - client          : logging in using static token
INFO       - 2023-09-12 13:40:06,030 - gateway         : Shard ID None has connected to Gateway (Session ID: e95567c1c1ef725d056d3384fb24c2f2).
ERROR      - 2023-09-12 13:50:05,118 - bot             : Ignoring exception in command play
Traceback (most recent call last):
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devgopal/Desktop/Music Bot/cogs/music.py", line 67, in play
    await self.play_next_track()
  File "/Users/devgopal/Desktop/Music Bot/cogs/music.py", line 75, in play_next_track
    await self.vc.play(next_track)
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/wavelink/player.py", line 403, in play
    'encodedTrack': track.encoded,
                    ^^^^^^^^^^^^^
AttributeError: 'YouTubePlaylist' object has no attribute 'encoded'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'play' raised an exception: AttributeError: 'YouTubePlaylist' object has no attribute 'encoded'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/discord/ext/commands/hybrid.py", line 438, in _invoke_with_namespace
    value = await self._do_call(ctx, ctx.kwargs)  # type: ignore
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/devgopal/Desktop/Music Bot/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.ext.commands.errors.HybridCommandError: Hybrid command raised an error: Command 'play' raised an exception: AttributeError: 'YouTubePlaylist' object has no attribute 'encoded'
